#!/bin/bash -e

awk '{printf"%3d   %3d   %d  %7.6f   %7.6f   %7.6f\n", $1, $2, $3, $4, $5, $6}' Result > ResultFinal
s=$(awk 'BEGIN{sum=0}{sum+=$6}END{print sum/NR}' ResultFinal)
awk -v var="$s" '{print $6/var*0.528591}' ResultFinal > newGaussHeight
